const ACCESS_PENDING = 'pending'
const ACCESS_APPROVED = 'approved'
const ACCESS_REJECTED = 'rejected'

const ES_ACCESS_PENDING = 'Pendiente'
const ES_ACCESS_APPROVED = 'Aprobado'
const ES_ACCESS_REJECTED = 'Rechazado'

export { ACCESS_PENDING, ACCESS_APPROVED, ACCESS_REJECTED, ES_ACCESS_APPROVED, ES_ACCESS_PENDING, ES_ACCESS_REJECTED }
