const TIME_KEY_VALID = 3600
const KEY_REDIS_LAB = 'lab'
const KEY_REDIS_USER = 'user'
const KEY_REDIS_ROLE = 'role'
const KEY_REDIS_KARDEX = 'kadex'
const KEY_REDIS_SAMPLE = 'sample'
const KEY_REDIS_PAYMENT = 'payment'
const KEY_REDIS_REACTIVE = 'reactive'
const KEY_REDIS_ACCESS_LAB = 'acess_lab'
const KEY_REDIS_ACCESS_LAB_STATUS = 'acess_lab_status'
const KEY_REDIS_REQUEST_REACTIVE = 'reactive_request'
const KEY_REDIS_CONSUMPTION_REACTIVE = 'consumption_reactive'

export {
	KEY_REDIS_LAB,
	TIME_KEY_VALID,
	KEY_REDIS_USER,
	KEY_REDIS_ROLE,
	KEY_REDIS_KARDEX,
	KEY_REDIS_SAMPLE,
	KEY_REDIS_PAYMENT,
	KEY_REDIS_REACTIVE,
	KEY_REDIS_ACCESS_LAB,
	KEY_REDIS_REQUEST_REACTIVE,
	KEY_REDIS_ACCESS_LAB_STATUS,
	KEY_REDIS_CONSUMPTION_REACTIVE,
}
