import { ACCESS_MANAGER, DIRECTOR, GENERAL_ADMIN, SUPERVISOR, TECHNICAL_ANALYST } from '../../const/roles.const.js'
import {
	ACCESO,
	DERLYS,
	ERIKAC,
	FABIANB,
	GALOP,
	GOD,
	ISABELP,
	MAFERQ,
	PAOLAW,
	SANTIAGOS,
} from '../../const/credential_user.const.js'

const user_data = [
	{
		full_name: 'God',
		identification_card: '0000000000',
		email: GOD,
		password: GOD,
		roles: [GENERAL_ADMIN],
	},
	{
		full_name: 'Galo Paez',
		identification_card: '0000000001',
		phone: '0000000001',
		email: GALOP,
		password: GALOP,
		code: 'DG',
		roles: [DIRECTOR],
	},
	{
		full_name: 'Fabián Bayas',
		identification_card: '0000000002',
		phone: '0000000002',
		email: FABIANB,
		password: FABIANB,
		code: 'FB',
		roles: [DIRECTOR],
	},
	{
		full_name: 'Isabel Paredes',
		identification_card: '0000000003',
		phone: '0000000003',
		email: ISABELP,
		password: ISABELP,
		code: 'SL',
		roles: [SUPERVISOR, TECHNICAL_ANALYST],
	},
	{
		full_name: 'Mafer Quinteros',
		identification_card: '0000000004',
		phone: '0000000004',
		email: MAFERQ,
		password: MAFERQ,
		code: 'MQ',
		roles: [TECHNICAL_ANALYST],
	},
	{
		full_name: 'Erika Cortez',
		identification_card: '0000000005',
		phone: '0000000005',
		email: ERIKAC,
		password: ERIKAC,
		code: 'EC',
		roles: [TECHNICAL_ANALYST],
	},
	{
		full_name: 'Paola Wilcaso',
		identification_card: '0000000006',
		phone: '0000000006',
		email: PAOLAW,
		password: PAOLAW,
		code: 'PW',
		roles: [TECHNICAL_ANALYST],
	},
	{
		full_name: 'Santiago S',
		identification_card: '0000000007',
		phone: '0000000007',
		email: SANTIAGOS,
		password: SANTIAGOS,
		code: 'SS',
		roles: [TECHNICAL_ANALYST],
	},
	{
		full_name: 'Derly Silva',
		identification_card: '0000000008',
		phone: '0000000008',
		email: DERLYS,
		password: DERLYS,
		code: 'DS',
		roles: [TECHNICAL_ANALYST],
	},
	{
		full_name: 'Administrador Acceso',
		identification_card: '0000000009',
		phone: '0000000009',
		email: ACCESO,
		password: ACCESO,
		code: 'AA',
		roles: [ACCESS_MANAGER],
	},
]

export { user_data }
